version: '3'
services:

  mongo-server:
    image: mongo:latest
    container_name: engine-specs-api-db
    restart: unless-stopped
    expose:
      - "27017"
    volumes:
      - /Users/marcelocorpucci/Repositories/engine-specs-api-docker:/data/db
    networks:
      - docker_network

  app:
    build: .
    container_name: engine-specs-api
    restart: unless-stopped
    ports:
      - "8050:8050"
    environment:
      FLASK_APP: "api.main:create_app('PROD')"
      FLASK_RUN_PORT: 8050
    command: "flask run --host 0.0.0.0"
    depends_on:
      - mongo-server
    networks:
      - docker_network

networks:
  docker_network:
    driver: bridge